@MyRecipe.Api_HostAddress = https://localhost:7123

### Register a New User
POST {{MyRecipe.Api_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "username": "chef_john",
  "email": "john@myrecipe.com",
  "password": "SecurePassword123!"
}

###

### Login User
POST {{MyRecipe.Api_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "john@myrecipe.com",
  "password": "SecurePassword123!"
}